---
- hosts: localhost
  tasks:
    - name: Установка sysstat
      apt:
        name: sysstat
        state: present
        update_cache: yes
      become: yes

    - name: Получение информации о CPU
      command: iostat -c
      register: CPU

    - name: Вывод информации о процессоре
      debug:
        msg: "{{ CPU.stdout }}"
