---
- name: Установка Berkeley DB
  hosts: localhost
  become: yes
  vars:
    версия_berkeley_db: "18.1.40"
    директория_установки: "/usr/local/BerkeleyDB.18.1"
    файл_бд: "/tmp/test_db.db"

  tasks:
    - name: Скачать архив
      get_url:
        url: "https://download.oracle.com/berkeley-db/db-{{ версия_berkeley_db }}.tar.gz"
        dest: "/tmp/db.tar.gz"

    - name: Распаковать архив
      unarchive:
        src: "/tmp/db.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Собрать и установить Berkeley DB
      shell: |
        cd /tmp/db-{{ версия_berkeley_db }}/build_unix &&
        ../dist/configure --prefix={{ директория_установки }} --disable-docs &&
        make -j$(nproc) &&
        make install || [ $? -eq 2 ]
      args:
        executable: /bin/bash

    - name: Удалить временные файлы
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/db.tar.gz"
        - "/tmp/db-{{ версия_berkeley_db }}"
      ignore_errors: yes

    - name: Настроить путь к библиотекам
      copy:
        dest: "/etc/ld.so.conf.d/bdb.conf"
        content: "{{ директория_установки }}/lib\n"

    - name: Обновить кэш библиотек
      command: ldconfig

    - name: Добавить тестовые данные в БД
      shell: |
        echo -e "key1=value1\nkey2=value2\ntest_key=test_value" |
        {{ директория_установки }}/bin/db_load -T -t hash {{ файл_бд }}
      args:
        executable: /bin/bash

    - name: Проверка создания БД
      debug:
        msg: "Тестовая база данных создана в {{ файл_бд }} с 3 записями"
